# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "É uma Sala de Teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/0992399d-4742-433e-9ae8-a19e2b33b24b/questions
Accept: application/json
Content-Type: application/json  

{
  "question": "vale a pena aprender python?"
}